# 1 Crear la clase calculadora con las funciones sumar, restar, multiplicar y dividir.
# Calculadora Simple y Sencillo
# Numeros a Sumar
# def suma(x, y):
#     return x + y

# Numeros de resta

# def resta(x, y):
#     return x - y

# Numeros de multiplicar


# def multiplicar(x, y):
#     return x * y

# Numeros que quieras dividir


# def divide(x, y):
#     return x / y

# Las Opciones.


# print("Seleccione una Opcion.")
# print("1.Suma")
# print("2.Resta")
# print("3.Multiplicar")
# print("4.Dividir")

# out = str("no")
# into = str("si")

# while True:
    # take input from the user
    # elegir = input("Elija opcion segun el orden(1/2/3/4): ")

    # if elegir in ('1', '2', '3', '4'):
    #     num1 = int(input("Ingrese Primer Numero: "))
    #     num2 = int(input("Ingrese Segundo Numero: "))
    #     if elegir == '1':
    #         print(num1, "+", num2, "=", suma(num1, num2))
    #     elif elegir == '2':
    #         print(num1, "-", num2, "=", resta(num1, num2))
    #     elif elegir == '3':
    #         print(num1, "*", num2, "=", multiplicar(num1, num2))
    #     elif elegir == '4':
    #         print(num1, "/", num2, "=", divide(num1, num2))

        # En caso quiera repetir las siguientes opciones presione si.
        
        # continuecalc = input("Desea Continuar? (Si/No): ")
        # if continuecalc == into:
        #     print("Continuando")
        # elif continuecalc == out:
        #     print("Saliendo")
            # break
    
    # else:
    #     print("Cometio un error, intente nuevamente.")


# Crear la clase persona con las funciones de comer, dormir y jugar. 

# class persona:
    
#     def __init__(self, comer, dormir, jugar):
#         self.comer = comer
#         self.dormir = dormir 
#         self.jugar 
#     def __str__(self):
        